version: '3'
services:
  webapp:
    container_name: "tl_wp"
    build: ./webapp
    depends_on:
      - database
      - nginx
    networks:
      - training_log

  database:
    container_name: "tl_db"
    build: ./database
    ports:
      - "3306:3306"
    networks:
      - training_log
    volumes:
      - ./database/mysql_init:/docker-entrypoint-initdb.d

  nginx:
    container_name: "tl_nginx"
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d/training_log.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - training_log

networks:
  training_log:
